server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reg?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: a123456.
    driver-class-name: com.mysql.jdbc.Driver
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true